<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_ahref  httpskatalon-demo-cura.herokuapp.c_bf49b4</name>
   <tag></tag>
   <elementGuidId>e3b84350-7836-4af0-9ecf-23625a9f5630</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='comment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d3f0c96d-e420-4f7a-a97a-b6c658983fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comment</value>
      <webElementGuid>899b72b5-1dc2-412f-a566-5a497f207f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>//a[@href = 'https://katalon-demo-cura.herokuapp.com/' and (text() = 'Go to Homepage' or . = 'Go to Homepage')]</value>
      <webElementGuid>3ba25c55-1146-483b-97e7-dd36d08f8e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comment&quot;)</value>
      <webElementGuid>4cb29b8a-8523-4fe7-a5c5-10477e96c063</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='comment']</value>
      <webElementGuid>e997bbde-08d8-43d5-a05d-c56813ccdb92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='summary']/div/div/div[6]/div[2]/p</value>
      <webElementGuid>aa468e5a-7649-4566-b4ff-1bfdfc76fb61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comment'])[1]/following::p[1]</value>
      <webElementGuid>a14fcfcc-1d54-4319-9a31-3b695b8dcf18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit Date'])[1]/following::p[2]</value>
      <webElementGuid>69977a2a-2c7d-4586-ac92-f7056aa868b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to Homepage'])[1]/preceding::p[1]</value>
      <webElementGuid>8e3bbb11-ae0a-4f2a-9a22-7ce584470e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CURA Healthcare Service'])[3]/preceding::p[2]</value>
      <webElementGuid>8a932267-422c-49fd-8e0a-991ecf9e5039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/p</value>
      <webElementGuid>d16ff21e-52f0-4865-8eb8-bf04d3778704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'comment' and (text() = concat(&quot;//a[@href = &quot; , &quot;'&quot; , &quot;https://katalon-demo-cura.herokuapp.com/&quot; , &quot;'&quot; , &quot; and (text() = &quot; , &quot;'&quot; , &quot;Go to Homepage&quot; , &quot;'&quot; , &quot; or . = &quot; , &quot;'&quot; , &quot;Go to Homepage&quot; , &quot;'&quot; , &quot;)]&quot;) or . = concat(&quot;//a[@href = &quot; , &quot;'&quot; , &quot;https://katalon-demo-cura.herokuapp.com/&quot; , &quot;'&quot; , &quot; and (text() = &quot; , &quot;'&quot; , &quot;Go to Homepage&quot; , &quot;'&quot; , &quot; or . = &quot; , &quot;'&quot; , &quot;Go to Homepage&quot; , &quot;'&quot; , &quot;)]&quot;))]</value>
      <webElementGuid>e3a74b95-4e11-4ce4-a830-321960ecde0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
